import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import { UserTypeProvider } from "@/Contexts/UserTypeContext";
import Footer from "@/Components/Footer/Footer";
import Providers from "@/Redux/providers";
import { AuthProvider } from "@/Contexts/AuthContext";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  preload: true,
});

// const montserratMono = Montserrat({
//   variable: "--font-montserrat-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} flex flex-col min-h-screen`}>
        <UserTypeProvider>
          <Header />
          <main className="flex-1">
            <AuthProvider>
              <Providers>{children}</Providers>
            </AuthProvider>
          </main>
          <Footer />
        </UserTypeProvider>
      </body>
    </html>
  );
}
//  <AuthProvider>
//           {children}
//         </AuthProvider>
